/**
 * @author Saki
 * @date 2019-04-19 18:38:17
 * @Last Modified by: Saki
 * @Last Modified time: 2019-05-17 13:29:07
 *
 * Application index file – the app execution starts here
 * auto-generated by create-react-app script 
 */

// The following import is only for ie11 compatibility
import 'core-js';

import React from 'react';
import ReactDOM from 'react-dom';

import App from './App.js';

ReactDOM.render(<App />, document.getElementById('container'));

// eof
